-- Product-only store: categories + unlimited product media
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists category_id bigint references public.categories(id) on delete set null;

create table if not exists public.product_media (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  media_type text not null check (media_type in ('image','video')),
  url text not null,
  title text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists products_category_id_idx on public.products(category_id);
create index if not exists product_media_product_id_idx on public.product_media(product_id);

alter table public.categories enable row level security;
alter table public.product_media enable row level security;

drop policy if exists "Public can read categories" on public.categories;
create policy "Public can read categories" on public.categories for select using (true);

drop policy if exists "Public can read product media" on public.product_media;
create policy "Public can read product media" on public.product_media for select using (true);

insert into public.categories (name, slug) values
  ('لوازم ورزشی', 'sports'),
  ('گل و گیاه', 'plants'),
  ('لوازم کامپیوتری', 'computer-accessories'),
  ('لوازم خانگی', 'home-appliances')
on conflict (slug) do nothing;
